title: "UCSB CS16"
course: "CS16"
github_url: https://github.com/ucsb-cs16/ucsb-cs16.github.io

# Change this every quarter!

qtr: "M18"
this_quarter_class_url: https://ucsb-cs16-m18.github.io
github_url: https://github.com/ucsb-cs16-m18/ucsb-cs16-m18.github.io
piazza_url: https://piazza.com/ucsb/summer2018/cmpsc16/home
gauchospace_course_page: https://gauchospace.ucsb.edu/courses/course/view.php?id=26795
gradescope_class_url: https://gradescope.com/courses/19473

# Other settings

legacy_wiki_name: 16wiki
legacy_wiki_url: "https://foo.cs.ucsb.edu/16wiki" 

on_campus: http://proquest.safaribooksonline.com
off_campus: http://proquest.safaribooksonline.com.proxy.library.ucsb.edu:2048/

instructor: https://ucsb-cs16.github.io/instructor

#kramdown:
#  parse_block_html: true

exclude: ['vendor', 'setup.sh', 'jekyll.sh']

timezone: America/Los_Angeles

collections:
  info:
    output: true
    permalink: /info/:path/

  topics:
    output: true
    permalink: /topics/:path/

  textbooks:
    output: true
    permalink: /textbooks/:path/

  resources:
    output: true
    permalink: /resources/:path/
    
  instructors:
    output: true
    permalink: /instructors/:path/


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  - scope:
      path: ""
      type: topics
    values:
      layout: topic
  - scope:
      path: ""
      type: info
    values:
      layout: topic
  - scope:
      path: ""
      type: resources
    values:
      layout: topic
  - scope:
      path: ""
      type: instructor
    values:
      layout: topic
