title: "UCSB CS16"
course: "CS16"
github_url: https://github.com/ucsb-cs16/ucsb-cs16.github.io

# Change this every quarter!

qtr: "M18"

instances:
  -
    instructor: Mirza
    site_url: https://ucsb-cs16-f18-mirza.github.io
    github_org:
       name: ucsb-cs16-f18-mirza
       url: https://github.com/ucsb-cs16-f18-mirza
    piazza_url:  https://piazza.com/ucsb/fall2018/cs16nichols/home
    gradescope_url: https://www.gradescope.com/courses/25325       
  -
    instructor: Nichols
    github_org:
       name: ucsb-cs16-f18-nichols
       url: https://github.com/ucsb-cs16-f18-nichols
    piazza_url:  https://piazza.com/ucsb/fall2018/cs16nichols/home
    gradescope_url: https://www.gradescope.com/courses/25325


# Other settings

instructor: https://ucsb-cs16.github.io/instructor

#kramdown:
#  parse_block_html: true

exclude: ['vendor', 'setup.sh', 'jekyll.sh']

timezone: America/Los_Angeles

collections:
  info:
    output: true
    permalink: /info/:path/

  topics:
    output: true
    permalink: /topics/:path/

  textbooks:
    output: true
    permalink: /textbooks/:path/

  resources:
    output: true
    permalink: /resources/:path/
    
  instructors:
    output: true
    permalink: /instructors/:path/


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  - scope:
      path: ""
      type: topics
    values:
      layout: topic
  - scope:
      path: ""
      type: info
    values:
      layout: topic
  - scope:
      path: ""
      type: resources
    values:
      layout: topic
  - scope:
      path: ""
      type: instructor
    values:
      layout: topic
